-- MySQL Script generated by MySQL Workbench
-- Wed Sep 27 19:19:24 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema controle-chamadas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema controle-chamadas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `controle-chamadas` DEFAULT CHARACTER SET utf8 ;
USE `controle-chamadas` ;

-- -----------------------------------------------------
-- Table `controle-chamadas`.`nivel_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controle-chamadas`.`nivel_curso` (
  `idnivel_curso` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idnivel_curso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controle-chamadas`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controle-chamadas`.`curso` (
  `idcurso` INT NOT NULL AUTO_INCREMENT,
  `idnivel_curso` INT NOT NULL,
  `nome_curso` VARCHAR(255) NULL,
  `carga_horaria` INT NULL,
  `porcentagem_tolerancia_falta` INT NULL,
  PRIMARY KEY (`idcurso`),
  INDEX `fk_curso_nivel_curso1_idx` (`idnivel_curso` ASC),
  CONSTRAINT `fk_curso_nivel_curso1`
    FOREIGN KEY (`idnivel_curso`)
    REFERENCES `controle-chamadas`.`nivel_curso` (`idnivel_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controle-chamadas`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controle-chamadas`.`turma` (
  `idturma` INT NOT NULL AUTO_INCREMENT,
  `idcurso` INT NOT NULL,
  `código` VARCHAR(255) NOT NULL,
  `nome_turma` VARCHAR(255) NOT NULL,
  `dias_semana` VARCHAR(255) NULL,
  `horario_aulas` TIME NULL,
  `qtde_alunos_ativos` VARCHAR(255) NULL,
  PRIMARY KEY (`idturma`),
  INDEX `fk_turma_curso1_idx` (`idcurso` ASC),
  CONSTRAINT `fk_turma_curso1`
    FOREIGN KEY (`idcurso`)
    REFERENCES `controle-chamadas`.`curso` (`idcurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controle-chamadas`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controle-chamadas`.`aluno` (
  `idaluno` INT NOT NULL AUTO_INCREMENT,
  `nome_aluno` VARCHAR(255) NULL,
  PRIMARY KEY (`idaluno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controle-chamadas`.`matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controle-chamadas`.`matricula` (
  `idmatricula` INT NOT NULL AUTO_INCREMENT,
  `idturma` INT NOT NULL,
  `idaluno` INT NOT NULL,
  `ativo` TINYINT NULL,
  INDEX `fk_turma_has_aluno_aluno1_idx` (`idaluno` ASC),
  INDEX `fk_turma_has_aluno_turma_idx` (`idturma` ASC),
  PRIMARY KEY (`idmatricula`),
  CONSTRAINT `fk_turma_has_aluno_turma`
    FOREIGN KEY (`idturma`)
    REFERENCES `controle-chamadas`.`turma` (`idturma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turma_has_aluno_aluno1`
    FOREIGN KEY (`idaluno`)
    REFERENCES `controle-chamadas`.`aluno` (`idaluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controle-chamadas`.`aula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controle-chamadas`.`aula` (
  `idaula` INT NOT NULL AUTO_INCREMENT,
  `idturma` INT NOT NULL,
  `data_aula` DATE NULL,
  `conteudo` VARCHAR(255) NULL,
  PRIMARY KEY (`idaula`),
  INDEX `fk_aula_turma1_idx` (`idturma` ASC),
  CONSTRAINT `fk_aula_turma1`
    FOREIGN KEY (`idturma`)
    REFERENCES `controle-chamadas`.`turma` (`idturma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controle-chamadas`.`chamada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controle-chamadas`.`chamada` (
  `idchamada` INT NOT NULL AUTO_INCREMENT,
  `idaula` INT NOT NULL,
  `horario_chamada` TIME NULL,
  PRIMARY KEY (`idchamada`),
  INDEX `fk_chamada_aula1_idx` (`idaula` ASC),
  CONSTRAINT `fk_chamada_aula1`
    FOREIGN KEY (`idaula`)
    REFERENCES `controle-chamadas`.`aula` (`idaula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controle-chamadas`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controle-chamadas`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NULL,
  `senha` VARCHAR(255) NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controle-chamadas`.`matricula_chamada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controle-chamadas`.`matricula_chamada` (
  `idmatricula_chamada` INT NOT NULL AUTO_INCREMENT,
  `matricula_idmatricula` INT NOT NULL,
  `chamada_idchamada` INT NOT NULL,
  INDEX `fk_matricula_has_chamada_chamada1_idx` (`chamada_idchamada` ASC),
  INDEX `fk_matricula_has_chamada_matricula1_idx` (`matricula_idmatricula` ASC),
  PRIMARY KEY (`idmatricula_chamada`),
  CONSTRAINT `fk_matricula_has_chamada_matricula1`
    FOREIGN KEY (`matricula_idmatricula`)
    REFERENCES `controle-chamadas`.`matricula` (`idmatricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matricula_has_chamada_chamada1`
    FOREIGN KEY (`chamada_idchamada`)
    REFERENCES `controle-chamadas`.`chamada` (`idchamada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
